name: armTemplateDeployment

on: 
  push: 
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group rg-githubactions
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: cfbb1f92-dbc1-4688-833a-beb14362c6e6
          region: West US 3
          template: ./arm-templates/resourcegroup.json
          deploymentName: rg-githubactions

      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          subscriptionId: cfbb1f92-dbc1-4688-833a-beb14362c6e6
          template: ./arm-templates/storageaccount.json
          parameters: 
            ./arm-templates/storageaccount.parameters.json
            storageAccountName=learningstor002
            location=West US 2
          deploymentMode: incremental
